apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: docker-build
  labels:
    "pipelines.openshift.io/used-by": "build-cloud"
    "pipelines.openshift.io/runtime": "generic"
    "pipelines.openshift.io/strategy": "docker"
spec:
  params:
    - description: 'Source Repository URL'
      name: git-url
      type: string
    - description: 'Revision of the Source Repository'
      name: revision
      type: string
      default: ""
    - description: 'Fully Qualified Output Image'
      name: output-image
      type: string
    - description: The path to your source code
      name: path-context
      type: string
      default: .
    - description: Path to the Dockerfile
      name: dockerfile
      type: string
      default: Dockerfile
    - description: Force rebuild image
      name: rebuild
      type: string
      default: "false"
  tasks:
    - name: appstudio-init
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/build-definitions.git
          - name: pathInRepo
            value: task/init/0.1/init.yaml
      params:
        - name: image-url
          value: "$(params.output-image)"
        - name: rebuild
          value: "$(params.rebuild)"
    - name: clone-repository
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/build-definitions.git
          - name: pathInRepo
            value: task/git-clone/0.1/git-clone.yaml
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: "$(params.revision)"
      runAfter:
        - appstudio-init
      workspaces:
        - name: output
          workspace: workspace
        - name: basic-auth
          workspace: git-auth
      when:
        - input: $(tasks.appstudio-init.results.build)
          operator: in
          values: ["true"]
    - name: appstudio-configure-build
      taskRef:
        name: configure-build
      runAfter:
        - clone-repository
      when:
        - input: $(tasks.appstudio-init.results.build)
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: workspace
        - name: registry-auth
          workspace: registry-auth
    - name: build-container
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/build-definitions.git
          - name: pathInRepo
            value: task/appstudio-buildah/0.1/appstudio-buildah.yaml
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.path-context)
        - name: BUILD_EXTRA_ARGS
          value: "$(tasks.appstudio-configure-build.results.buildah-auth-param)"
        - name: PUSH_EXTRA_ARGS
          value: "$(tasks.appstudio-configure-build.results.buildah-auth-param)"
      runAfter:
        - appstudio-configure-build
      workspaces:
        - name: source
          workspace: workspace
      when:
        - input: $(tasks.appstudio-init.results.build)
          operator: in
          values: ["true"]
  finally:
    - name: show-summary
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/build-definitions.git
          - name: pathInRepo
            value: task/summary/0.1/summary.yaml
      params:
      - name: pipeline-run-name
        value: "$(context.pipelineRun.name)"
      - name: git-url
        value: "$(params.git-url)"
      - name: image-url
        value: $(params.output-image)
  results:
    - name: IMAGE_URL
      value: "$(tasks.build-container.results.IMAGE_URL)"
    - name: IMAGE_DIGEST
      value: "$(tasks.build-container.results.IMAGE_DIGEST)"
    - name: CHAINS-GIT_URL
      value: "$(tasks.clone-repository.results.url)"
    - name: CHAINS-GIT_COMMIT
      value: "$(tasks.clone-repository.results.commit)"
  workspaces:
    - name: workspace
    - name: registry-auth
      optional: true
    - name: git-auth
      optional: true
